<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\ConfirmPasswordController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\QuestionBankController;
use App\Http\Controllers\Admin\TopicController;
use App\Http\Controllers\Admin\ChapterController;
use App\Http\Controllers\Admin\SubjectController;
use App\Http\Controllers\Admin\TradeController;
use App\Http\Controllers\Admin\TradeGroupController;
use App\Http\Controllers\Admin\TestController;
Route::get('/', function () {return view('user-pages.home');})->name('home');
Route::get('/about', function () {return view('user-pages.about');})->name('about');
Route::get('/contact', function () {return view('user-pages.contact');})->name('contact');
Route::get('/services', function () {return view('user-pages.services');})->name('services');
Route::get('/gallery', function () {return view('user-pages.gallery');})->name('gallery');


Route::get('/comi', '\App\Http\Controllers\TestController@convertWithPandoc')->name('convert.docx.to.text');

// Auth Routes (auto-generated by Auth::routes())
Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login']);
Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
Route::get('/register', [RegisterController::class, 'showRegistrationForm'])->name('register');
Route::post('/register', [RegisterController::class, 'register']);
Route::get('/password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
Route::post('/password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
Route::get('/password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('/password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');
Route::get('/password/confirm', [ConfirmPasswordController::class, 'showConfirmForm'])->name('password.confirm');
Route::post('/password/confirm', [ConfirmPasswordController::class, 'confirm']);

// Default Home Route
// Route::get('/home', [HomeController::class, 'index'])->name('home');
// Route::get('/profile', [AdminController::class, 'profile'])->name('profile');
// Admin Home Route (Fixed)
Route::get('/admin/home', [AdminController::class, 'index'])->name('admin.home');

Route::prefix('admin')->middleware(['auth'])->group(function () {
    Route::get('/users', [UserController::class, 'index'])->name('admin.users.index');
    Route::get('/users/create', [UserController::class, 'create'])->name('admin.users.create');
    Route::post('/users', [UserController::class, 'store'])->name('admin.users.store');
    Route::get('/users/{user}/edit', [UserController::class, 'edit'])->name('admin.users.edit');
    Route::put('/users/{user}', [UserController::class, 'update'])->name('admin.users.update');
    Route::delete('/users/{user}', [UserController::class, 'destroy'])->name('admin.users.destroy');


    // Question Bank Routes
    Route::get('/question-bank', [QuestionBankController::class, 'index'])->name('admin.question-bank.index');
    Route::get('/question-bank/create', [QuestionBankController::class, 'create'])->name('admin.question-bank.create');
    Route::post('/question-bank', [QuestionBankController::class, 'store'])->name('admin.question-bank.store');
    Route::get('/question-bank/{question}/edit', [QuestionBankController::class, 'edit'])->name('admin.question-bank.edit');
    Route::put('/question-bank/{question}', [QuestionBankController::class, 'update'])->name('admin.question-bank.update');
    Route::delete('/question-bank/{question}', [QuestionBankController::class, 'destroy'])->name('admin.question-bank.destroy');

    // Add more routes (edit, update, destroy) later if needed


    //for getting dropdown data
    Route::get('/trades', [QuestionBankController::class, 'getTrades'])->name('admin.trades');
    Route::get('/subjects', [QuestionBankController::class, 'getSubjects'])->name('admin.subjects');
    Route::get('/chapters', [QuestionBankController::class, 'getChapters'])->name('admin.chapters');
    Route::get('/topics', [QuestionBankController::class, 'getTopics'])->name('admin.topics');


    Route::get('/fetch-trades', [QuestionBankController::class, 'getTradess'])->name('admin.fetch-trades');
    Route::get('/fetch-subjects', [QuestionBankController::class, 'getSubjectss'])->name('admin.fetch-subjects');
    Route::get('/fetch-chapters', [QuestionBankController::class, 'getChapterss'])->name('admin.fetch-chapters');
    Route::get('/fetch-topics', [QuestionBankController::class, 'getTopicss'])->name('admin.fetch-topics');


    // Trade Groups
    Route::get('/trade-groups', [TradeGroupController::class, 'index'])->name('admin.trade-groups.index');
    Route::get('/trade-groups/create', [TradeGroupController::class, 'create'])->name('admin.trade-groups.create');
    Route::post('/trade-groups', [TradeGroupController::class, 'store'])->name('admin.trade-groups.store');
    Route::get('/trade-groups/{tradeGroup}/edit', [TradeGroupController::class, 'edit'])->name('admin.trade-groups.edit');
    Route::put('/trade-groups/{tradeGroup}', [TradeGroupController::class, 'update'])->name('admin.trade-groups.update');
    Route::delete('/trade-groups/{tradeGroup}', [TradeGroupController::class, 'destroy'])->name('admin.trade-groups.destroy');

    // Trades
    Route::get('/trades', [TradeController::class, 'index'])->name('admin.trades.index');
    Route::get('/trades/create', [TradeController::class, 'create'])->name('admin.trades.create');
    Route::post('/trades', [TradeController::class, 'store'])->name('admin.trades.store');
    Route::get('/trades/{trade}/edit', [TradeController::class, 'edit'])->name('admin.trades.edit');
    Route::put('/trades/{trade}', [TradeController::class, 'update'])->name('admin.trades.update');
    Route::delete('/trades/{trade}', [TradeController::class, 'destroy'])->name('admin.trades.destroy');

    // Subjects
    Route::get('/subjects', [SubjectController::class, 'index'])->name('admin.subjects.index');
    Route::get('/subjects/create', [SubjectController::class, 'create'])->name('admin.subjects.create');
    Route::post('/subjects', [SubjectController::class, 'store'])->name('admin.subjects.store');
    Route::get('/subjects/{subject}/edit', [SubjectController::class, 'edit'])->name('admin.subjects.edit');
    Route::put('/subjects/{subject}', [SubjectController::class, 'update'])->name('admin.subjects.update');
    Route::delete('/subjects/{subject}', [SubjectController::class, 'destroy'])->name('admin.subjects.destroy');

    // Chapters
    Route::get('/chapters', [ChapterController::class, 'index'])->name('admin.chapters.index');
    Route::get('/chapters/create', [ChapterController::class, 'create'])->name('admin.chapters.create');
    Route::post('/chapters', [ChapterController::class, 'store'])->name('admin.chapters.store');
    Route::get('/chapters/{chapter}/edit', [ChapterController::class, 'edit'])->name('admin.chapters.edit');
    Route::put('/chapters/{chapter}', [ChapterController::class, 'update'])->name('admin.chapters.update');
    Route::delete('/chapters/{chapter}', [ChapterController::class, 'destroy'])->name('admin.chapters.destroy');

    // Topics
    Route::get('/topics', [TopicController::class, 'index'])->name('admin.topics.index');
    Route::get('/topics/create', [TopicController::class, 'create'])->name('admin.topics.create');
    Route::post('/topics', [TopicController::class, 'store'])->name('admin.topics.store');
    Route::get('/topics/{topic}/edit', [TopicController::class, 'edit'])->name('admin.topics.edit');
    Route::put('/topics/{topic}', [TopicController::class, 'update'])->name('admin.topics.update');
    Route::delete('/topics/{topic}', [TopicController::class, 'destroy'])->name('admin.topics.destroy');


    // New bulk upload routes
    Route::get('/question-bank/bulk-upload', [QuestionBankController::class, 'bulkUpload'])->name('admin.question-bank.bulk-upload');
    Route::post('/question-bank/bulk-import', [QuestionBankController::class, 'bulkImport'])->name('admin.question-bank.bulk-import');

    Route::get('/tests', [TestController::class, 'index'])->name('admin.tests.index');
    Route::get('/tests/create', [TestController::class, 'create'])->name('admin.tests.create');
    Route::post('/tests', [TestController::class, 'store'])->name('admin.tests.store');
    Route::get('/tests/{test}/bulk-upload-questions', [TestController::class, 'bulkUploadQuestions'])->name('admin.tests.bulk-upload-questions');
    Route::post('/tests/{test}/bulk-import-questions', [TestController::class, 'bulkImportQuestions'])->name('admin.tests.bulk-import-questions');
    Route::post('/tests/{test}/toggle-publish', [TestController::class, 'togglePublish'])->name('admin.tests.toggle-publish');

    Route::get('/tests/{test}/questions', [TestController::class, 'showQuestions'])->name('admin.tests.show-questions');

    Route::get('/tests/{test}/edit', [TestController::class, 'edit'])->name('admin.tests.edit');
    Route::put('/tests/{test}', [TestController::class, 'update'])->name('admin.tests.update'); // New
    Route::get('/tests/{test}/view-details', [TestController::class, 'viewDetails'])->name('admin.tests.view-details');
    Route::delete('/tests/{test}', [TestController::class, 'destroy'])->name('admin.tests.destroy');



    Route::post('/tests/{test}/switch-language', [TestController::class, 'switchLanguage'])->name('admin.tests.switch-language');

});
